[lints.rust]
missing_docs = "warn"

[lints.clippy]
# https://rust-lang.github.io/rust-clippy/master/index.html#/
unwrap_used = "deny"
indexing_slicing = "deny"
inefficient_to_string = "warn"
use_self = "warn"
implicit_clone = "warn"
